export const allSoftSkills = [
  "Communication",
  "Teamwork",
  "Problem Solving",
  "Critical Thinking",
  "Adaptability",
  "Time Management",
  "Creativity",
  "Leadership",
  "Collaboration",
  "Emotional Intelligence",
  "Flexibility",
  "Positive Attitude",
  "Effective Listening",
  "Empathy",
  "Conflict Resolution",
  "Decision Making",
  "Attention to Detail",
  "Open-mindedness",
  "Resilience",
  "Patience",
  "Networking",
  "Presentation Skills",
  "Negotiation",
  "Customer Service",
  "Cultural Awareness",
  "Motivation",
  "Stress Management",
  "Self-Discipline",
  "Self-Motivation",
  "Work Ethic",
  "Professionalism",
  "Interpersonal Skills",
  "Innovation",
  "Adaptability",
  "Proactive",
  "Time Management",
  "Networking",
  "Collaboration",
  "Conflict Resolution",
  "Decision Making",
  "Attention to Detail",
  "Leadership",
  "Critical Thinking",
  "Problem Solving",
  "Emotional Intelligence",
  "Resilience",
];