export const allTechSkills = [
    "JavaScript",
    "HTML5",
    "CSS3",
    "React.js",
    "Angular",
    "Vue.js",
    "Node.js",
    "Express.js",
    "MongoDB",
    "SQL",
    "RESTful API",
    "GraphQL",
    "Git",
    "Webpack",
    "Babel",
    "TypeScript",
    "Redux",
    "Jest",
    "Mocha",
    "Chai",
    "Docker",
    "AWS",
    "Firebase",
    "Responsive Web Design",
    "Sass",
    "LESS",
    "Webpack",
    "Jenkins",
    "Continuous Integration/Continuous Deployment (CI/CD)",
    "Agile/Scrum",
    "Linux/Unix",
    "JSON",
    "XML",
    "OAuth",
    "WebSockets",
    "Testing (Unit, Integration, E2E)",
    "Data Structures",
    "Algorithms",
    "Design Patterns",
    "Performance Optimization",
    "Security Best Practices",
    "Web Accessibility (WCAG)",
    "Mobile Development (React Native, Flutter)",
    "Responsive Design",
    "Cross-browser Compatibility",
    "Progressive Web Apps (PWAs)",
    "Blockchain",
    "Machine Learning (TensorFlow, PyTorch)",
    "AR/VR Development",
    "Microservices Architecture",
    "Serverless Architecture",
    "GraphQL",
    "WebAssembly",
    "D3.js",
    "Three.js",
    "Socket.io",
    "Nginx",
    "OAuth 2.0",
    "JSON Web Tokens (JWT)",
  ];