export const popularSoftSkills = [
    "Communication",
    "Teamwork",
    "Problem Solving",
    "Critical Thinking",
    "Adaptability",
    "Time Management",
    "Creativity",
    "Leadership",
    "Collaboration",
    "Emotional Intelligence",
];

export const top10TechnicalSkills = [
    "JavaScript",
    "Python",
    "Java",
    "React.js",
    "Node.js",
    "HTML5",
    "CSS3",
    "Git",
    "SQL",
    "AWS",
];

export const level = [
    'Beginner',
    'Intermediate',
    'Expert'
]

export const worldLanguages = [
    "English",
    "Spanish",
    "Mandarin Chinese",
    "Hindi",
    "Arabic",
    "Portuguese",
    "Bengali",
    "Russian",
    "Japanese",
    "Punjabi",
    "German",
    "Javanese",
    "Telugu",
    "Marathi",
    "Turkish",
    "Tamil",
    "Urdu",
    "French",
    "Italian",
    "Vietnamese",
    "Korean",
    "Telugu",
    "Cantonese",
    "Hausa",
    "Yoruba",
    "Swahili",
    "Dutch",
    "Thai",
    "Polish",
    "Malayalam",
    "Filipino",
    "Persian",
    "Swedish",
    "Gujarati",
    "Kannada",
    "Odia",
    "Ukrainian",
    "Burmese",
    "Malay",
    "Pashto",
    "Amharic",
    "Sindhi",
    "Farsi",
    "Yiddish",
    "Zulu",
];

export const softSkills = [
    "Communication",
    "Teamwork",
    "Problem Solving",
    "Critical Thinking",
    "Adaptability",
    "Time Management",
    "Creativity",
    "Leadership",
    "Collaboration",
    "Emotional Intelligence",
    "Flexibility",
    "Positive Attitude",
    "Effective Listening",
    "Empathy",
    "Conflict Resolution",
    "Decision Making",
    "Attention to Detail",
    "Open-mindedness",
    "Resilience",
    "Patience",
    "Networking",
    "Presentation Skills",
    "Negotiation",
    "Customer Service",
    "Cultural Awareness",
    "Motivation",
    "Stress Management",
    "Self-Discipline",
    "Self-Motivation",
    "Work Ethic",
    "Professionalism",
    "Interpersonal Skills",
    "Innovation",
    "Adaptability",
    "Proactive",
    "Time Management",
    "Networking",
    "Collaboration",
    "Conflict Resolution",
    "Decision Making",
    "Attention to Detail",
    "Leadership",
    "Critical Thinking",
    "Problem Solving",
    "Emotional Intelligence",
    "Resilience",
];

export const technicalSkills = [
    "JavaScript",
    "HTML5",
    "CSS3",
    "React.js",
    "Angular",
    "Vue.js",
    "Node.js",
    "Express.js",
    "MongoDB",
    "SQL",
    "RESTful API",
    "GraphQL",
    "Git",
    "Webpack",
    "Babel",
    "TypeScript",
    "Redux",
    "Jest",
    "Mocha",
    "Chai",
    "Docker",
    "AWS",
    "Firebase",
    "Responsive Web Design",
    "Sass",
    "LESS",
    "Webpack",
    "Jenkins",
    "Continuous Integration/Continuous Deployment (CI/CD)",
    "Agile/Scrum",
    "Linux/Unix",
    "JSON",
    "XML",
    "OAuth",
    "WebSockets",
    "Testing (Unit, Integration, E2E)",
    "Data Structures",
    "Algorithms",
    "Design Patterns",
    "Performance Optimization",
    "Security Best Practices",
    "Web Accessibility (WCAG)",
    "Mobile Development (React Native, Flutter)",
    "Responsive Design",
    "Cross-browser Compatibility",
    "Progressive Web Apps (PWAs)",
    "Blockchain",
    "Machine Learning (TensorFlow, PyTorch)",
    "AR/VR Development",
    "Microservices Architecture",
    "Serverless Architecture",
    "GraphQL",
    "WebAssembly",
    "D3.js",
    "Three.js",
    "Socket.io",
    "Nginx",
    "OAuth 2.0",
    "JSON Web Tokens (JWT)",
];